version: "3"
services:
  database_mongo:
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=database
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
